# Generated by Django 3.0.6 on 2020-05-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastsroasts',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
